name: infrastructure master deployment
on: 
  workflow_call:
    inputs:
      access_key_id: 
        description: AWS_ACCESS_KEY_ID
        required: true
        type: string
      
      secret_access_key: 
        description: AWS_SECRET_ACCESS_KEY
        required: true
        type: string
jobs:
  m_build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Get code 
        uses: actions/checkout@v3
      - name: install terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.access_key_id }}
          aws-secret-access-key: ${{ inputs.secret_access_key }}
          aws-region: us-east-1
      - name: terraform init
        run: terraform init
      - name: terraform validate
        run: terraform validate
      - name: terraform plan
        run: terraform plan
  
  m_deploy_to_dev:
    runs-on: ubuntu-latest
    needs: m_build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Get code 
        uses: actions/checkout@v3
      - name: install terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.access_key_id }}
          aws-secret-access-key: ${{ inputs.secret_access_key }}
          aws-region: us-east-1
      - name: terraform init
        run: terraform init
      - name: terraform validate
        run: terraform validate
      - name: terraform plan
        run: terraform plan
      - name: applying changes
        run: terraform apply -auto-approve
